---
  classes:
    - "general"
    - "timezone"
    - "user_account"
    - "user_account::vagrant"
    - "kegbot"
  general::ensure: "latest"
  timezone::timezone: "US/Central"
  user_account::users:
    - "root"
    - "vagrant"
  #kegbot::database_type: "mysql"

