---
  classes:
    - "general"
    - "timezone"
    - "user_account"
    - "user_account::vagrant"
    - "kegbot"
  general::ensure: "latest"
  timezone::timezone: "US/Central"
  user_account::users:
    root: {}
    vagrant:
      sudoers: true
      sudoers_allow_non_tty: true
  kegbot_instances:
    chi_51: 
      start_server: false

